algoritmo "semnome"
// Função :
// Autor :
// Data : 15/03/2022
// Seção de Declarações 
var
A, B, C:inteiro
inicio
// Seção de Comandos 
A <- 2
B <- 3
C <- 5
escreval((A=B) ou (C>A))
escreval(.>. maior que)
escreval(.<. menor que)
escreval(.>=. maior ou igual a)
escreval(.<=. menor ou igual a)
escreval(ordem de precedencia)
escreval(aritmeticos: .()., .^., .*/., .+-.)
escreval(relacionais: todos )
escreval(lógico: e. .ou., .nao.)

fimalgoritmo
